---
title: "Project Proposal"
author: "Leslie Kang, Connor Booher, Ali Sadek"
date: "3/21/2021"
output:
  html_document: default
  pdf_document: default
---

# Proposal 1: Scrabble Data
We retrieved this data from fivethirtyeight.com under an article called "How
‘Qi’ And ‘Za’ Changed Scrabble." The author of this article, Oliver Roeder,
collected this data by web-scraping 1,542,642 tournament games between
1973 and 2017 from cross-tables.com. This data set contains 19 variables, with a
few that may be of interest.
We may look at `winnerid` (the numerical ID of the winning player),
`winnerscore` (score of winning player), `date`, and `lexicon` (a binary
variable indicating whether the game was played with the North American lexicon
or not).
*Please note that the data set is big and we were not able to upload it into our
`data/` folder. We have communicated this with Professor Smith.
\
There were two major dictionary changes that took place between 1972 and 2017.
What we want to know: Which edition of the Official Scrabble Players Dictionary
or OSPD had the greater influence on increasing average winning score, edition
4 or edition 5 of OSPD?
\
$H_0: \mu_4 - \mu_1 = \mu_5 - \mu_2$
\
$H_A: \mu_4 - \mu_1 > \mu_5 - \mu_2$
\
Where $\mu_4$ = 3 year average winning score after 4th edition publication,
$\mu_1$ = 3 year average winning score before 4th edition publication, $\mu_5$ =
3 year average winning score after 5th edition publication, $\mu_2$ = 3 year
average winning score before 5th edition publication.

# Proposal 2

We retrieved these data from fivethirtyeight.com under an article called
"The Dollar-And-Cents Case Against Hollywood’s Exclusion of Women." The data
includes one csv file pulled from an API on the Bechdel Test website and another
file with various movie statistics pulled from IMDb. The former is a score named 
after the famous cartoonist Allison Bechdel according the following criteria:
`0` = unscored, `1.` It has to have at least two [named] women in it, 
`2.` Who talk to each other, `3.` About something besides a man. 

This 'test' was created to determine whether a movie's female characters were
permitted any depth--something, for myriad reasons, that's still unlikely. 
The IMDb dataset will be used to look at the relationship between a movie's 
gender for `director` and `writer`. We hypothesize that the presence of a 
female writer and/or director increases the likelihood that a given film passes 
the Bechdel test.

$H_0: p_f = p_m$
\
$H_A: p_f > p_m$

Where $p_f$ is the proportion of movies with a female director and/or writer
that passes the Bechdel test and $p_m$ is the proportion of movies with a male 
director and writer that passes the Bechdel test. 

# Proposal 3
We retrieved this data from who.int under the Global Youth Tobacco Survey. The
authors of this dataset collected the data through written surveys handed out in
schools throughout Brazil. The survey contains dozens of questions about the
history of tobacco use for these students, such as the amount of times they have
smoked, how many of their peers smoke, etc...

Some variables that would be interesting to look at are `CR3` and its
relationship to `CR26` and `BRR22`. `CR3` encodes the students response to how
many days they had smoked in the past month. `Q32` encodes the students response
to how many of their close friends smoke cigarettes. `Q33` encodes the students
response to a question about their parents' history of tobacco use. We
hypothesize that students with close friends/parents who smoke are likely to
report having smoked more than students that do not have close friends/parents 
who smoke.

$H_0: p_s = p_n$
\
$H_A: p_s > p_n$

Where $p_s$ is the number of days smoked in the past month by students who have
close friends and/or parents who smoke and $p_n$ is the number of days smoked in
the past month by students who do not have close friends and/or parents who 
smoke. 

```{r uploading_dat}
library(tidyverse)
library(infer)
data <- read.csv("data/BRASILIA_11.csv")
```

